/**
 * invoiceGenerator.ts
 * Features: Multi-page support, Unit labels, Subtitles, and High-Contrast Table.
 */

import { jsPDF } from 'jspdf';
import type { BusinessProfile } from '../config/businessProfile';

export interface OrderItem {
  name: string;
  quantity: number;
  unitPrice?: number;
  rowTotal?: number;
  category?: string;
  priceUnit?: string;
}

function formatQuantityLabel(quantity: number, priceUnit?: string): string {
  if (!priceUnit || String(priceUnit).trim() === '' || priceUnit === 'None') {
    return `${quantity} Units`;
  }
  return `${quantity} ${String(priceUnit).trim()}`;
}

export interface Order {
  id: string;
  customer_name: string;
  customer_whatsapp?: string;
  items?: OrderItem[];
  total_amount?: number;
  created_at: string;
}

const MARGIN = 16;
const PAGE_BREAK_THRESHOLD = 260; // MM before jumping to new page

// ─── Helpers ────────────────────────────────────────────────────────────────

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('en-IN', {
    day: 'numeric', month: 'long', year: 'numeric',
  });
}

function renderTextToImage(text: string, fontSize: number, color: string, bold: boolean) {
  try {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) return null;
    const scale = 4;
    const weight = bold ? '700' : '400';
    const font = `${weight} ${fontSize}px -apple-system, sans-serif`;
    ctx.font = font;
    const metrics = ctx.measureText(text);
    const cw = metrics.width + fontSize * 0.4;
    const ch = fontSize * 1.5;
    canvas.width = cw * scale;
    canvas.height = ch * scale;
    ctx.scale(scale, scale);
    ctx.font = font;
    ctx.fillStyle = color;
    ctx.textBaseline = 'middle';
    ctx.fillText(text, (fontSize * 0.2), ch / 2);
    return { dataUrl: canvas.toDataURL('image/png'), width: cw, height: ch };
  } catch { return null; }
}

function addUniformText(
  pdf: jsPDF, text: string, x: number, y: number, 
  sizeMm: number, color: string, bold = false, align: 'left' | 'center' | 'right' = 'left'
) {
  const img = renderTextToImage(text, 48, color, bold);
  if (!img) return;
  const wMm = (img.width / img.height) * sizeMm;
  let drawX = x;
  if (align === 'center') drawX = x - wMm / 2;
  if (align === 'right') drawX = x - wMm;
  pdf.addImage(img.dataUrl, 'PNG', drawX, y - sizeMm / 2, wMm, sizeMm);
}

// ─── Component Renderers ─────────────────────────────────────────────────────

function drawHeader(pdf: jsPDF, order: Order, business: BusinessProfile, pageWidth: number) {
  const headerH = 48;
  pdf.setFillColor(15, 23, 42); 
  pdf.rect(0, 0, pageWidth, headerH, 'F');

  addUniformText(pdf, (business.businessName || 'Your Business').toUpperCase(), MARGIN, 20, 8, '#FFFFFF', true);

  pdf.setFillColor(22, 163, 74); 
  pdf.rect(0, headerH, pageWidth, 3, 'F');

  const bx = pageWidth - MARGIN;
  addUniformText(pdf, 'INVOICE', bx, 15, 4, '#94A3B8', true, 'right');
  addUniformText(pdf, `INV-${order.id.substring(0, 8).toUpperCase()}`, bx, 24, 7, '#FFFFFF', true, 'right');
  addUniformText(pdf, formatDate(order.created_at), bx, 34, 5, '#CBD5E1', false, 'right');
}

function drawTableHeader(pdf: jsPDF, y: number, pageWidth: number) {
  const contentW = pageWidth - 2 * MARGIN;
  pdf.setFillColor(241, 245, 249); // Lighter background for header
  pdf.rect(MARGIN, y, contentW, 14, 'F');
  
  const hY = y + 7;
  const colQty = MARGIN + contentW * 0.65;
  const colRate = MARGIN + contentW * 0.82;
  const colTotal = MARGIN + contentW;
  
  // INCREASED FONT SIZE FOR HEADINGS
  addUniformText(pdf, 'ITEM DESCRIPTION', MARGIN + 4, hY, 4.5, '#0F172A', true);
  addUniformText(pdf, 'QTY', colQty, hY, 4.5, '#0F172A', true, 'center');
  addUniformText(pdf, 'RATE', colRate, hY, 4.5, '#0F172A', true, 'center');
  addUniformText(pdf, 'TOTAL', colTotal - 4, hY, 4.5, '#0F172A', true, 'right');
  
  return y + 14;
}

function drawFooter(pdf: jsPDF, pageWidth: number, pageHeight: number) {
  const footerH = 15;
  const footerY = pageHeight - footerH;

  // Differentiation band
  pdf.setFillColor(248, 250, 252);
  pdf.rect(0, footerY, pageWidth, footerH, 'F');
  pdf.setDrawColor(226, 232, 240);
  pdf.line(0, footerY, pageWidth, footerY);

  const textY = footerY + (footerH / 2) + 1;
  addUniformText(pdf, 'This is a computer generated document.', MARGIN, textY, 3, '#94A3B8');
  
  const brandX = pageWidth - MARGIN;
  addUniformText(pdf, 'Generated by ', brandX - 18, textY, 3.2, '#64748B', false, 'right');
  addUniformText(pdf, 'CatShare', brandX, textY, 3.2, '#16A34A', true, 'right');
}

// ─── Main Logic ──────────────────────────────────────────────────────────────

export async function generateInvoicePDF(order: Order, business: BusinessProfile, symbol: string): Promise<Blob> {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  drawHeader(pdf, order, business, pageWidth);

  // Bill To (Large Heading)
  let currentY = 65;
  addUniformText(pdf, 'BILL TO', MARGIN, currentY, 4.5, '#64748B', true);
  currentY += 9;
  addUniformText(pdf, order.customer_name, MARGIN, currentY, 7, '#000000', true);
  currentY += 18;

  // Table Start
  currentY = drawTableHeader(pdf, currentY, pageWidth);

  const items = order.items || [];
  const contentW = pageWidth - 2 * MARGIN;
  const colQty = MARGIN + contentW * 0.65;
  const colRate = MARGIN + contentW * 0.82;
  const colTotal = MARGIN + contentW;
  const rowH = 16;

  items.forEach((item, index) => {
    // Check for page break
    if (currentY > PAGE_BREAK_THRESHOLD) {
      drawFooter(pdf, pageWidth, pageHeight);
      pdf.addPage();
      currentY = 20; // Margin at top of new page
      currentY = drawTableHeader(pdf, currentY, pageWidth);
    }

    const midY = currentY + (rowH / 2);
    pdf.setDrawColor(241, 245, 249);
    pdf.line(MARGIN, currentY + rowH, MARGIN + contentW, currentY + rowH);

    // 1. Item Name + Subtitle (Category)
    const displayTitle = item.category ? `${item.name} (${item.category})` : item.name;
    addUniformText(pdf, displayTitle, MARGIN + 4, midY, 5, '#000000', true);

    // 2. Qty + Unit
    const qtyLabel = formatQuantityLabel(item.quantity, item.priceUnit);
    addUniformText(pdf, qtyLabel, colQty, midY, 5, '#000000', false, 'center');
    
    // 3. Rate (Now Black)
    const rate = `${symbol}${ (item.unitPrice || 0).toLocaleString() }`;
    addUniformText(pdf, rate, colRate, midY, 5, '#000000', false, 'center');

    // 4. Total
    const total = `${symbol}${ (item.rowTotal || (item.unitPrice || 0) * item.quantity).toLocaleString() }`;
    addUniformText(pdf, total, colTotal - 4, midY, 5, '#000000', true, 'right');

    currentY += rowH;
  });

  // Totals & Thank You Box (Ensure they don't get cut off)
  if (currentY > 230) {
    drawFooter(pdf, pageWidth, pageHeight);
    pdf.addPage();
    currentY = 20;
  }

  currentY += 15;
  addUniformText(pdf, 'GRAND TOTAL', pageWidth - MARGIN - 55, currentY, 5.5, '#64748B', true);
  const totalStr = `${symbol}${ (order.total_amount || 0).toLocaleString('en-IN', { minimumFractionDigits: 2 }) }`;
  addUniformText(pdf, totalStr, pageWidth - MARGIN, currentY, 8.5, '#16A34A', true, 'right');

  // Thank You Box
  currentY += 15;
  pdf.setFillColor(248, 250, 252);
  (pdf as any).roundedRect(MARGIN, currentY, pageWidth - (MARGIN * 2), 20, 2, 2, 'F');
  pdf.setFillColor(22, 163, 74);
  pdf.rect(MARGIN, currentY, 2.5, 20, 'F');
  addUniformText(pdf, 'Thank you for your business!', MARGIN + 8, currentY + 7, 4.5, '#16A34A', true);
  addUniformText(pdf, 'Please contact us if you have any questions regarding this invoice.', MARGIN + 8, currentY + 14, 3.8, '#64748B');

  // Final page footer
  drawFooter(pdf, pageWidth, pageHeight);

  return pdf.output('blob') as Blob;
}
